# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stack View' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stack View
pod 'SnapKit', '~> 5.6.0'
end
