# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneSignalLibrarySwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end

end